apiVersion: v1
kind: Pod
metadata:
  name: gop-file-server
  labels:
    app: gop-file-server
spec:
  containers:
    - name: file-server
      image: kodekloud/fileserver
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: data-store
          mountPath: /web
  volumes:
    - name: data-store
      persistentVolumeClaim:
        claimName: data-pvc